### ISSUE TITLE
AttributeError on datetime object in seed-data.py

### ISSUE THREAD

**Issue by geewey** [square/squaredev-sales-report#5]
Issue:
An `AttributeError` is thrown when running the data seeding script command `python ./seed-data.py --seed` 

Error logs show the issue in the seed_inventory method on line 114:
```
$ python ./seed-data.py --seed
Successfully created customers
Successfully created catalog
Traceback (most recent call last):
  File "./seed-data.py", line 344, in <module>
    seed_inventory()
  File "./seed-data.py", line 114, in seed_inventory
    "occurred_at": datetime.datetime.now(datetime.UTC)
AttributeError: module 'datetime' has no attribute 'UTC'
```

Suggested fix:
Update to `datatime.timezone.utc` from the incorrect `datetime.UTC` so that a valid datetime object is returned:
`"occurred_at": datetime.datetime.now(datetime.timezone.utc)`

After making this change locally, the seeding completed successfully. I was able to follow the rest of the steps and retrieve the sales data.

**Comment by zenmasterjobo** [comment]
hi @geewey 

Thanks for opening this issue! I'm not running into this problem myself with the code as it is.. I'm using Python version 3.12.2

While searching, I actually found this in the python docs - https://docs.python.org/3/library/datetime.html#datetime.UTC

looks like it was added in Python 3.11 - I will update the code with your suggestion though, as the code will work more broadly with other / older versions in Python 3.

Thanks for your contribution! 😄
